data_configs:
  lang_pair: "en-zh"
  train_data:
    - "/home/user_data/weihr/NMT_DATA_PY3/1.34M/train/zh.under50.txt"
    - "/home/user_data/weihr/NMT_DATA_PY3/1.34M/train/en.under50.txt"
  valid_data:
    - "/home/user_data/weihr/NMT_DATA_PY3/1.34M/test/MT03/zh.0"
    - "/home/user_data/weihr/NMT_DATA_PY3/1.34M/test/MT03/en.0"
  bleu_valid_reference: "/home/user_data/weihr/NMT_DATA_PY3/1.34M/test/MT03/en."
  dictionaries:
    - "/home/user_data/weihr/NMT_DATA_PY3/1.34M/dict/dict.zh.json"
    - "/home/user_data/weihr/NMT_DATA_PY3/1.34M/dict/dict.en.json"
  bpe_codes:
    - ""
    - ""
  n_words:
    - 30000
    - 30000
  max_len:
    - -1
    - -1
  num_refs: 4
  eval_at_char_level: false

model_configs:
  model: Transformer
  n_layers: 6
  n_head: 8
  d_word_vec: &dim 512
  d_model: *dim
  d_inner_hid: 2048
  dropout: 0.1
  proj_share_weight: false
  label_smoothing: 0.1

optimizer_configs:
  optimizer: "adam"
  learning_rate: 2.0
  grad_clip: 5.0
  optimizer_params: ~

training_configs:
  max_epochs: 1000000
  shuffle: true
  use_bucket: false # Whether to use bucket. If true, model will run faster while a little bit performance regression.
  buffer_size: 100 # Only valid when use_bucket is true.
  shard_size: -1 # Shard size. Negative value if closed.
  batch_size: 50
  valid_batch_size: 50
  bleu_valid_batch_size: 10
  bleu_valid_warmup: 10000 # Start to do BLEU validation after those steps
  disp_freq: 100 # Frequency to print information
  save_freq: 1000 # Frequency to save the model
  loss_valid_freq: &decay_freq 100
  bleu_valid_freq: 1000
  early_stop_patience: 20
  decay_method: "noam" # ["loss" | "noam"]
  decay_freq: 1 # Must be 1 when decay_method is 1
  decay_warmup_steps: 3 # Make sense only decay_method is noam
  lrate_decay_patience: 30
  min_lrate: -1.0 # Make sense only decay_method is loss

