data_configs:
  lang_pair: "de-en"
  train_data:
    - "/home/user_data/wengrx/WMT17-TREN/corpus.tc.bpe.tr"
    - "/home/user_data/wengrx/WMT17-TREN/corpus.tc.bpe.en"
  valid_data:
    - "/home/user_data/wengrx/WMT17-TREN/newstest2016.tc.bpe.tr"
    - "/home/user_data/wengrx/WMT17-TREN/newstest2016.tc.bpe.en"
  bleu_valid_reference: "/home/user_data/wengrx/WMT17-TREN/newstest2016.tc.en"
  dictionaries:
    - "/home/user_data/wengrx/WMT17-TREN/corpus.tc.bpe.tr.json"
    - "/home/user_data/wengrx/WMT17-TREN/corpus.tc.bpe.en.json"
  bpe_codes:
    - ""
    - ""
  use_char:
    - false
    - false
  n_words:
    - 30000
    - 30000
  max_len:
    - 80
    - 80
  num_refs: 1
  eval_at_char_level: false

model_configs:
  model: Transformer
  n_layers: 6
  n_head: 8
  d_word_vec: &dim 512
  d_model: *dim
  d_inner_hid: 2048
  dropout: 0.1
  proj_share_weight: false
  label_smoothing: 0.1
  wp_loss: true
  ae_loss: false
  pretrain_path: /home/user_data/wengrx/model/base_tren/transformer_base_tren.best.tpz
  auto_encoder_path: /home/user_data/wengrx/model/tren_ae_en/transformer_tren_ae_en.best.tpz

optimizer_configs:
  optimizer: "adam"
  learning_rate: 1.0
  grad_clip: -1.0
  optimizer_params: ~
  schedule_method: noam # ["loss" | "noam" | ~], see details in ./lr_schedule_examples
  scheduler_configs:
    d_model: *dim
    warmup_steps: 4000
    schedule_freq: 1

training_configs:
  max_epochs: 100
  shuffle: true
  use_bucket: false # Whether to use bucket. If true, model will run faster while a little bit performance regression.
  buffer_size: 100 # Only valid when use_bucket is true.
  shard_size: -1 # Shard size. Negative value if closed.
  batch_size: 25
  valid_batch_size: 25
  bleu_valid_batch_size: 10
  bleu_valid_warmup: 10000 # Start to do BLEU validation after those steps
  bleu_valid_configs:
    bleu_script: "multi-bleu"
    lowercase: true
    postprocess: false
  disp_freq: 100 # Frequency to print information
  save_freq: 1000 # Frequency to save the model
  loss_valid_freq: &decay_freq 100
  bleu_valid_freq: 1000
  early_stop_patience: 100000000000
