data_configs:
  lang_pair: "zh-en"
  train_data:
    - "/home/user_data/weihr/NMT_DATA_PY3/WMT-ZH-EN/no_un/zh.txt"
    - "/home/user_data/weihr/NMT_DATA_PY3/WMT-ZH-EN/no_un/en.txt"
  valid_data:
    - "/home/user_data/weihr/NMT_DATA_PY3/WMT-ZH-EN/no_un/newsdev2017.tok.zh"
    - "/home/user_data/weihr/NMT_DATA_PY3/WMT-ZH-EN/no_un/newsdev2017.tok.en"
  bleu_valid_reference: "/home/user_data/weihr/NMT_DATA_PY3/WMT-ZH-EN/no_un/newsdev2017.en"
  vocabularies:
    - type: "bpe"
      dict_path: "/home/user_data/weihr/NMT_DATA_PY3/WMT-ZH-EN/no_un/vocab.zh.json"
      codes: "/home/user_data/weihr/NMT_DATA_PY3/WMT-ZH-EN/no_un/zh.codes"
      max_n_words: -1
    - type: "bpe"
      dict_path: "/home/user_data/weihr/NMT_DATA_PY3/WMT-ZH-EN/no_un/vocab.en.json"
      codes: "/home/user_data/weihr/NMT_DATA_PY3/WMT-ZH-EN/no_un/en.codes"
      max_n_words: -1
  max_len:
    - 100
    - 100
  num_refs: 1
  eval_at_char_level: false

model_configs:
  model: Transformer
  n_layers: 6
  n_head: 8
  d_word_vec: 512
  d_model: 512
  d_inner_hid: 2048
  dropout: 0.1
  tie_embedding: false
  proj_share_weight: true
  label_smoothing: 0.1

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.2
  grad_clip: -1.0
  optimizer_params: ~
  schedule_method: noam
  scheduler_configs:
    d_model: 512
    warmup_steps: 8000

training_configs:
  max_epochs: 1000000
  shuffle: true
  use_bucket: true
  batching_key: "tokens"
  batch_size: 2500
  update_cycle: 10
  valid_batch_size: 30
  bleu_valid_batch_size: 30
  bleu_valid_warmup: 1 # Start to do BLEU validation after those steps
  bleu_valid_configs:
    beam_size: 4
    max_steps: 150
    postprocess: true
    sacrebleu_args: ""
  num_kept_checkpoints: 1
  disp_freq: 100 # Frequency to print information
  save_freq: 500 # Frequency to save the model
  loss_valid_freq: 500
  bleu_valid_freq: 500
  early_stop_patience: 50
